Donate page
ooni/ooni.org pull request #723
Opened 2020-12-16 17:26 UTC by Vivsss

2021-02-09 10:05 UTC, hellais commented on content/donate/_index.md
> +  link: "https://ooni.org/post/egypt-censors/"
These links should not be here

2021-02-09 10:05 UTC, hellais commented on content/donate/_index.md
> +* [Research](https://ooni.org/reports/) on censorship events worldwide
This content should not be present here.

2021-02-09 10:06 UTC, hellais commented on content/donate/stickers/index.md
> +---
Are these still necessary?

2021-02-09 10:07 UTC, hellais commented on layouts/donate/single.html
> +{{ end }}
I don't think this page is necessary.

2021-02-09 10:08 UTC, hellais commented on layouts/section/donate.html
> +        {{ .Content }}
Can we put all the content inside of the markdown file so it's easier to edit and translate?

2021-02-09 10:08 UTC, hellais commented on content/donate/_index.md
> +* [Research](https://ooni.org/reports/) on censorship events worldwide
I now realise this is needed, but should include also the content that is currently inlined in the HTML.

2021-02-09 10:09 UTC, hellais commented on layouts/section/donate.html
> +
This is a left-over broken javascript code, which needs to be removed.

2021-02-09 10:10 UTC, hellais requested changes
Should remove all the dead code and ensure that all the copy/content of the donate page is included inside of the `content/donate/_index.md`

2021-02-09 10:17 UTC, hellais commented on content/donate/_index.md
> +maindescr: "As a non-profit, we rely on donations from people like you to defend a free and open internet for all. By donating to OONI, you support:"
Can we move this into the content?

2021-02-09 10:25 UTC, hellais commented on layouts/section/donate.html
> +                <li>Bank Transfer / SEPA</li>
Missing link and page for this

2021-02-09 10:25 UTC, hellais commented on layouts/section/donate.html
> +<script src="https://www.paypal.com/sdk/js?client-id=ATd3rHkGu0i2Q1KsJpk3at-MR6pFfBIYgrJuDFsxVau4_lS_KEhydMUIu0lWKCcPwNvc9Fmyp6JUCV-Q&vault=true"  data-namespace="paypal_sdk"></script>
We don't need any javascript since we are using a more simple button

2021-02-11 16:08 UTC, hellais commented on layouts/section/donate.html
> +           <h3>{{ .Params.Thanks }}</h3>
This parameter can go in the markdown directly

2021-02-11 16:09 UTC, hellais commented on content/donate/_index.md
> +thanks: "Thank you for supporting the OONI-verse!"
This can go inside of the body

2021-11-30 17:47 UTC, agrabeli requested changes
I've reviewed and edited the copy. The cancel page though needs to be deleted since we're removing the paypal option.

2021-12-08 13:54 UTC, merged